### ISSUE TITLE
Log In: Pre-selection of server deleted

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#10]
Testserver: qa-gluons  and spot
Test date: 04.08.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: user (admin) 

Action:  Log in page Labcam
-> "other user" -> enter user account in https.//spot.mpdl.mpg.de/rest -> Log out

Observation:
Selection set back to "qa-gluons"

Expected result: if user leaves other server, Labcam has the server setting saved for re-log In and user doesn't have to select "other server" again

**Comment by liyyil** [comment]
Tested with HTC:
case 1: log out from gluons 
On login page, "GLUONS" is chosen, if I switch to "Other Server" URL shows gluons URL

case 2: log out from spot
On login page, "Other Server" is chosen, URL shows spot URL.
==============================================
It remebers the serverUrl.
A micro change to case 1:
 On login page, "GLUONS" is chosen, if I switch to "Other Server" URL shows "http://"
