### ISSUE TITLE
Change collection during automatic upload not possible

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#11]
Testserver: qa-gluons
Test date: 04.08.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: imeji admin

Action: change collectin during upload
-> automatic upload -> testbar running
-> menue -> "Automatic upload" -> select other collection -> Question if to continue running upload with same or new collection -> select new collection -> 

Observation: -> "Unfortunately, Labcam has stopped"
Expected result: no break down

**Comment by franziskaIpf** [comment]
- no break down 
- sometimes there are dublicates
- change collection -> "there are pictures waiting for upload, where to upload them?" -> take old collection -> progress bar has no text in it and only 0 and 100%

**Comment by franziskaIpf** [comment]
- more than 10 pictures -> sometimes message "There are still pictures waiting for upload. Go to Task Manger" like messge from login -> than no pictures shown -> dublicates

**Comment by franziskaIpf** [comment]
- number in recent processes is split into the two collections
