### ISSUE TITLE
"Server": insert space between author's name

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#110]
Testserver: qa-imeji.mpdl.mpg.de
Test date: 28.09.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: hofmann@mpdl.mpg.de

Action: 
start page > "server" -> "Bastiens collection" displayed "by BastienSaquet"

Observation: Space missing

**Comment by cafefish** [comment]
done: like imeji, it's shown in "FAMILYNAME, GIVENNAME"

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg./rest
Test date: 11.10.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

result: ok.
