### ISSUE TITLE
"Server": Optimize loading process for items of collection

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#112]
Testserver: qa-imeji.mpdl.mpg.de
Test date: 28.09.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: hofmann@mpdl.mpg.de

Actions:
start page -> "Server" -> select collection with more than 4 items -> long press on logo of collection -> item displayed in preview mode -> slide to next item -> to third item -> to forth item

Observation: Currently, only three items are available in this view at first sight, although more items are available in collection, optimize loading

**Comment by cafefish** [comment]
done

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg./rest
Test date: 11.10.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user
Result: ok, not reproducible anymore
