### ISSUE TITLE
[bug] QR-code not working

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#12]
Testserver: qa-gluons

Test date: 03.08.2016

Device: Tablet Nexus 9 Android 5.1.1.

User: user

Action: log in by QR code

-> LogIn -> QR-Code symbol -> “Unfortunately, LabCam has stopped”

Expected result: I can enter LabCam by QR code

**Comment by liyyil** [comment]
can't reproduce with samsung and htc, (login to qa-gluons)

**Comment by franziskaIpf** [comment]
instable behaviour- sometimes its working, sometimes not
