### ISSUE TITLE
problems with manual upload

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#120]
Testserver: qa-imeji.mpdl.mpg./rest
Test date: 11.10.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: manual upload
Observation:
select items -> manual upload -> select collection -> ok -> upload task bar is created, but actual upload is not realized.

coming back to my LabCam Account, I got the info that there are still upload tasks running , but going into the task manager, the tasks look like completed, but items were not uploaded and still in task manager listed. and in start page the task bar is still open saying "6 selected photo(s) uploading to 171011" at 100%. 

I am not sure, but maybe this issue came up after trying #119

automatic upload items are uploaded correctly and task is going to "recent uploads" correctly

Expected result: manual upload correctly performed and documented in task manager

**Comment by melissaMPDL** [comment]
Action:	
•	Select items  manual upload activated  select collection  ok 

Observation: 
•	Upload bar is created on front page
•	Upload until 100% 
•	Upload of photos in the collection 

Expectation: 
•	Manual upload correctly performed and documented in task manager (recent uploads)
