### ISSUE TITLE
Manual upload: collection selection is not kept

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#121]
Testserver: qa-imeji.mpdl.mpg./rest
Test date: 11.10.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: select collection for manual upload

Observations: 
-if I come back to select another collection, the earlier selected collection is not checked anymore
- name of collection's author is not displayed anymore

Expected result: system remembers which collection has been collected earlier.

**Comment by melissaMPDL** [comment]
Action: 
- select item(s)
- upload selected item(s) 
- select collection 

Observation: 
- last selected collection is targeted 

Expectation: 
- OK:  most recently selected collection is remembered through the system
