### ISSUE TITLE
delete multiple voice note for one item seems to provoke "unfortunately, LabCam has stopped"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#123]
Testserver: qa-imeji.mpdl.mpg./rest
Test date: 11.10.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: 
select several items -> create voice note -> all items are labeled woth voice note symbol -> select one item with symbol -> delete item -> "unfortunately, LabCam has stopped"

Observation:
from this moment on, I am not able to open other items as well. Only help: log out/Log in
 
If i add and delete a voice note only for one item, workflow correct

Expected result: i can delete a multiple voicenote for only one item

**Comment by melissaMPDL** [comment]
Action:	
•	Select several items
•	create voice-note for all selected items
•	all items are labeled with voice note symbol
•	select one item with symbol 
•	delete voice note for only one item 

Observation: 
•	voice note is deleted for the selected item

Expectation: 
•	ok, voice note deleted for the selected item 
•	voice notes of other items not affected 
•	system still running
