### ISSUE TITLE
[bug]list "recent processes" is cleared 

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#13]
Testcase CAM-42 Viewall recent processes

Testserver: qa-gluons

Test date: 03.08.2016

Device: Tablet Nexus 9Android 5.1.1.

User: user (withoutimeji admin rights)

Action: check"recent processes"

-> created somefinished upload tasks yesterday

Observation: This list was cleared when I came back today.

Expected result: All lately finished upload tasks are displayed.

**Comment by cafefish** [comment]
the list will be cleared if collection changed by AU

**Comment by liyyil** [comment]
fixed

**Comment by franziskaIpf** [comment]
need to be discussed!

-> why should list be cleared if AU changed? 
it is a completed task it should also stay in list
