### ISSUE TITLE
[bug]something fuzzy with upload task list

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#14]
Testserver: qa-gluons

Test date: 03.08.2016

Device: Tablet Nexus 9 Android 5.1.1.

Action: CAM 18 view all current upload tasks

CAM 42 -View all recent processes

Observation:

Somehow the naming of the upload tasks is sometimes incorrect: Labcam lables sometimes task as manual upload although it is an automatic upload

Example: User hofmann@mpdl.mpg.de -> „Automatic upload“ -> coll: „160802 mit def mdp"

-> camerasymbol took 11 pictures

-> Log out -> “There are still upload tasks …”-> Log out

-> LogIn -> Notification about open upload tasks”

-> selected one image for manual upload to be able to enter Task list

-> started automatic upload process again and upload is correctly finished

BUT: there is also a new item created in "Uploading tasks":

"11 selectedphotos upload to “160802 mit def mdp”" and item "Automatic upload to ..." stays in list after completion

And in “Recent processes”, only “11 selected Photos(s) uploaded to 160802 mit def mdp”is displayed, although this has been an automatic upload

**Comment by liyyil** [comment]
fix:
move login dialog to the main activity
click go into: open active task list
click ignore: stay in the main activity
