### ISSUE TITLE
[bug]transfer current processes - recent processes is not consistent 

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#15]
Testcase CAM-18 View all current upload tasks

Testserver: qa-gluons

Test date: 03.08.2016

Device: Tablet Nexus 9 Android 5.1.1.

User: user (without imeji admin rights)

Action: Check list "Uploading tasks" for running processes

Observation: sometimes finished tasks are not deleted from list "uploading tasks".

One time a not yet completed automatic upload task had already been moved to "recent processes".

it is not consistently reproducable.

Expected result: As soon as upload task is finished, it is deleted from "Uploading task" list and transferred to "Recent processes"

**Comment by franziskaIpf** [comment]
- same experience: finished tasks stay in uploading tasks
- Automatic upload to always there if Au is ON, i would do it just if au task is running-> otherwise its confusing
need to be discussed!

**Comment by liyyil** [comment]
#15
