### ISSUE TITLE
Au ON and no Col selected should not be possible

### ISSUE THREAD

**Issue by franziskaIpf** [MPDL/LabCam#25]
If i turn Automatic Upload ON - the Collection List should directely open

**Comment by cafefish** [comment]
login with username/passwword -> AU default On, it means collection list will be shown directly after login as Startpage => it is confused
=> should be discussed!!

**Comment by franziskaIpf** [comment]
- it is possible to add a pop up after login on local page: "Your automatic upload is switched on. Please go into the side bar and select a collecion"
- if i switch automatic upload on i would delete pop up "automatic upload is active please set a collection" and open page for select Collection directly -> one less step

**Comment by franziskaIpf** [comment]
Change into two options
1. Login with QR-Code, Automatic upload is On and Col already selected or Logout/Login again
-> Pop Up: Automatic Upload to Col X is active

2. Login with Username/Password, Automatic upload is On, no Col set
-> Local Page, Pop Up like Create Collection "Automatic upload is active, please set a Collection. If not, the automatic Upload will be switched off"
OK = Collection List show up 
Abbrechen= AU is OFF

**Comment by liyyil** [comment]
＃25

**Comment by cafefish** [comment]
![au settings](https://cloud.githubusercontent.com/assets/6161098/17737642/32f4fa26-648e-11e6-80b6-7d87c2b13fbf.png)

**Comment by liyyil** [comment]
#25
