### ISSUE TITLE
OCR function

### ISSUE THREAD

**Issue by cafefish** [MPDL/LabCam#28]
Refer:
Tesseract (https://code.google.com/archive/redirect/a/code.google.com/p/tesseract-ocr?movedTo=https:%2F%2Fgithub.com%2Ftesseract-ocr) -- Apache 2.0

**Comment by cafefish** [comment]
other references:
https://android-arsenal.com/details/3/324
https://android-arsenal.com/details/2/598
https://android-arsenal.com/tag/68

**Comment by cafefish** [comment]
Tesseract Tools for Android
https://github.com/rmtheis/tess-two

**Comment by soultice** [comment]
Refer
[Google Mobile Vision Text API for Android](https://codelabs.developers.google.com/codelabs/mobile-vision-ocr/#0)

[SampleCode](https://github.com/googlesamples/android-vision.git) (see ocr-reader-start/complete)
