### ISSUE TITLE
Pop Up: Logout

### ISSUE THREAD

**Issue by franziskaIpf** [MPDL/LabCam#34]
Message "There are still pictures waiting for uploading, are you sure you want to logout?" untruly pop up by every logout (AU on and AU off)

**Comment by hofmannc** [comment]
Testserver: qa-gluons
Test date: 19.09.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: gluons admin
Action: 
precondition: AU off, no uncompleted tasks in "Uploading tasks" -> "Logout"

result: cannot reproduce

**Comment by tonyqd** [comment]
Testserver: qa-gluons
 Test date: 04.10.2016 
 Device: Tablet Nexus 9 Android 5.0.1.
 User: normal user
 Action: 
 precondition: AU off, no uncompleted tasks in "Uploading tasks" -> "Logout"
                       AU on, no uncompleted tasks in "Uploading tasks" -> "Logout"

result: cannot reproduce
