### ISSUE TITLE
Activity destroyed

### ISSUE THREAD

**Issue by franziskaIpf** [MPDL/LabCam#38]
- App shows a blank page after taking pictures and returning to home page

**Comment by tonyqd** [comment]
This behaviour could not be regularly reproduced. It happens mostly when taking a lot of Pictures then immediately return to the main menu. The root cause is still under investigation.

**Comment by tonyqd** [comment]
After refactoring the code, I have not encountered this problem for quite a long time. I believe it has be resolved.
