### ISSUE TITLE
[bug] Metadata fields "Model" and "Exposure mode" not transfered to metadata profile

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#4]
Testserver: qa-gluons
Test date: 03.08.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: user with admin rights

Action: Upload fotos with metadata to collection without metadata profile

Observation: In some cases, the metadata field "Model" is added to metadata profile, sometimes not.
Metadata field "Exposure mode" is never included.

Expected result: Transfer of alll relevant metadata fields.

**Comment by liyyil** [comment]
meta fields added.

abandon android origin exif lib, intigrate metadata-extractor
