### ISSUE TITLE
"Uploading Tasks": manual upload stays although completed

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#40]
Testserver: qa-gluons
Test date: 19.09.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: gluons admin

Action: upload one item manually
-> select item -> "Upload" -> select collection -> task displayed in "Uploading tasks" section 

Observation: task is completed but stays in "Uploading tasks" section. this is not always reproducable: I've got one task which is still there although came back to "uploading tasks" several times. Some tasks are deleted only after the second or third time I come back, but most of them right after the completion (correct behaviour).

Expected result: task is not displayed in "Uploading tasks" anymore right after completion of upload.

**Comment by franziskaIpf** [comment]
can't reproduce

**Comment by tonyqd** [comment]
can't reproduce
