### ISSUE TITLE
collections created today are not displayed in tab "server"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#41]
Testserver: qa-gluons
Test date: 19.09.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: gluons admin

Action: Create new collection in qa-gluons
created 160919 and qa160919 

Observation: both collections are added to selection for automatic upload but are not displayed in "Server"
Expected result: I can check the uploaded files for the collections in tab "server"

**Comment by franziskaIpf** [comment]
can't reproduce

**Comment by tonyqd** [comment]
can't reproduce
