### ISSUE TITLE
Browse items by album breaks down

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#42]
Testserver: qa-gluons
Test date: 19.09.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: qa-gluons admin

Action: browse items by album

tab "local"/"Date" -> change to "Album" -> select  "Camera (1997)" -> scroll down

Observation: display of file "Camera (1997)" broke down while scrolling -> all items of "local"/date were also not displayed anymore (only dates) -> log out/log In -> it took around 3 minutes to get back the display of items of "local" and the display of albums in "album". 
reproducable, but later it took less than 3 minutes to recover.

Expected result: no breakdown while scrolling in big albums

**Comment by tonyqd** [comment]
this is a Performance issue, developer is already working on it.

**Comment by liyyil** [comment]
used scroll to load more mechanism, now load every 6 img(cell) at a time
