### ISSUE TITLE
Upload album twice: no notification

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#43]
Testserver: qa-gluons
Test date: 19.09.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: qa-gluons admin
Action: upload album to collection
uploaded album "data collector (3)" to "coll_gluons" -> selected same album again -> "upload" -> Taskbar is displayed and notification: "items uploaded sucessfully"

Observation: but items are not uploaded again to collection.
Expected result: if I upload duplicates, I get a notification

**Comment by franziskaIpf** [comment]
In recent processes dublicates are normal tasks 
Expected result: no notes are necessary
