### ISSUE TITLE
automatic upload reminder keeps popping up

### ISSUE THREAD

**Issue by tonyqd** [MPDL/LabCam#51]
everytime when user returns from one folder to main surface, the reminder "Automatic upload is active" will Show up, if this function is activated. I am not quite sure whether this is designed like this. But for me it will make sense to Display this message only when the user changes this Option.

**Comment by tonyqd** [comment]
I cannot find a way to avoid this problem. Since every time when we return to the view, oncreate will be called and this is the place where we have to implement this notification.

**Comment by soultice** [comment]
Suggest to either rewrite the activity into a fragment and keep it alive by [setRetainInstance()](https://developer.android.com/reference/android/app/Fragment.html#setRetainInstance(boolean)) or using a SharedPreference Boolean to log if the message has been displayed in the current session.

**Comment by tonyqd** [comment]
improved and tested
