### ISSUE TITLE
wrong notification about unfinished uploading task

### ISSUE THREAD

**Issue by tonyqd** [MPDL/LabCam#52]
When I reopen LabCam, there is a notification Shows "there are some uploading Tasks not be completed last time, you can restart them in your Taks Manager" 
Then I click on "GO INTO", it will lead me to "Uploading Tasks". I can see one entry which Shows "Automatic upload to test3", but I can do nothing about it. When I return everything Looks fine. But if I go to other apps and return back to labcam, the notification is still there. I can not get rid of it.

**Comment by liyyil** [comment]
handle failed tasks
