### ISSUE TITLE
Selection list does not include all collections (if user has more than 100 collections)

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#53]
Testserver: http://qa-edmond.mpdl.mpg.de/
Browser: ff
Test date: 27.10.2016
Device: Tablet Nexus 9
3.5.0.1-SNAPSHOT - build date 2016-10-27 09:06:12
User: standard user with +100 collections

Action: select new collection for automatic upload
-> Browser: user creates collection 
-> LabCam: Automatic upload -> select collection from list -> just created collection not available

Observation:
Labcam only transferred the first dozends collections for selection list. -> User cannot select the latest collections from list. 
Access to latest collection by QR-Code is not possible either.

Expected result: All collections of the user are available in listing.

**Comment by tonyqd** [comment]
If I remember correctly, Ying said that it has been fixed?
