### ISSUE TITLE
[bug] Automatic upload for shared collection not working

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#6]
Testserver: qa-gluons user: catherina@brauchma.net
Test date: 04.08.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User:
Action: Testcase CAM-44:Upload metadata to collection without MDP (user) (Tablet Nexus 9)
->other user shared the collection with user (read+update)
-> automatic upload to "coll 160804 without MDP shared with test001"
-> camera symbol
-> take fotos
Observation: no upload task running and no fotos uploaded
Manual upload works fine.

Expected result: User only with upload grants for the collectin is able to upload automatically

**Comment by liyyil** [comment]
can't reproduce with HTC tablet and Samsung
