### ISSUE TITLE
Login with QR code will directly enable automatic upload

### ISSUE THREAD

**Issue by tonyqd** [MPDL/LabCam#60]
Independent from the setting from user´s last setting, if user login with QR code, the automatic upload will be enabled. 

I am not quite sure whether this is designed like this or it is a bug

**Comment by soultice** [comment]
Recommending usage of SharedPreferences for this setting as well.

**Comment by tonyqd** [comment]
it is very easy to solve this bug. The question is only what we exactly want.

**Comment by soultice** [comment]
Considering security principles, the feature should be disabled by default.

**Comment by tonyqd** [comment]
According to Lu, it is actually designed like this.
