### ISSUE TITLE
Add Text Notes and Voice Notes for pictures

### ISSUE THREAD

**Issue by tonyqd** [MPDL/LabCam#63]
**Function**: Add/Edit text notes or voice notes to any selected pictures. Later on, the text notes and voice notes could be viewed in "Recent Text Notes" and "Recent Voice Notes". Inside "Recent Text Notes" and "Recent Voice Notes", all notes are listed and also could be deleted from there.   by manuell uploading text notes will be uploaded to imeji

**How does it work**
On the View LOCAL->Date, long press one picture, then select one or more pictures that you want to add notes to. On the top right corner of the screen select corresponding button to create text/voice notes. 

In case you select one picture and go inside the detail view of this picture(by short press this picture), you can also create text/voice notes by long pressing on this picture and then the button on the top right corner.

**Comment by cafefish** [comment]
[Test_Usercase_Notes.docx](https://github.com/MPDL/LabCam/files/766456/Test_Usercase_Notes.docx)

**Comment by cafefish** [comment]
[Test_Usercase_Notes.docx](https://github.com/MPDL/LabCam/files/766989/Test_Usercase_Notes.docx)
