### ISSUE TITLE
new Server Tab

### ISSUE THREAD

**Issue by cafefish** [MPDL/LabCam#64]
Server Tab with new GUI

**Comment by soultice** [comment]
Please elaborate further on this enhancement.

**Comment by cafefish** [comment]
go to "SERVER" Tab -> go to one collection -> go back to "SERVER" Tab, The whole list will be reloaded

**Comment by soultice** [comment]
Issue should be addressed in commit 3f3ea9661e2d055f81efb4f4854ae01b3cf5ba9c. Closing.
