### ISSUE TITLE
refresh picture list and checked the attached text/voice notes

### ISSUE THREAD

**Issue by tonyqd** [MPDL/LabCam#68]
If the picture is given with text/voice notes within LabCam and deleted by external apps, the created text/voice notes should also be deleted within LabCam.

**Comment by soultice** [comment]
Do you mean if the locally saved picture is deleted it should be deleted in LabCam as well?

**Comment by tonyqd** [comment]
Yes. Currently user cannot delete local picture in our app. But if the local picture is deleted somewhere else, and by coincident there was some notes attached to that picture in our app, in this situation, these notes are redundant since the attached picture does not exist any more. And these notes should be removed automatically

**Comment by soultice** [comment]
freezing this
