### ISSUE TITLE
Metadata "note" is not displayed in "view details"

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#73]
Testserver: qa-gluons
Test date: 22.02.2017
Device: Tablet Nexus 9 
User: standard user

Action: upload text note
qa-gluons -> create collection without metadata profile
labcam -> add text note to item -> upload manually to qa-gluons collection

Observation:
metadata field "Note" is added to metadata profile if you enter by "edit item", but item and value are not displayed in "view details" 

Expected result: added note is displayed in "view details" of item

**Comment by tonyqd** [comment]
It works fine with gluons, some adjustments are needed from the qa-gluons server
