### ISSUE TITLE
Problems after automatic upload of 20 items

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#74]
Testserver: qa-gluons
Test date: 19.09.2016 
Device: Tablet Nexus 9 
User: standard user

Action: automatic upload
select collection for automatic upload -> camera -> take 20 pictures -> automatic upload bar in task manager stays at 0%

select item for manual upload -> select same collection -> upload bar in "Local" says "1 selected photo(s) uploading to null" -> item in tab manager stays at 0%

qa-gluons: after logout/log task in task manager: 20 selected photos upload to [collection] -> "continue" -> upload sucessful

Observation:
Right after the first log In today, I tried automatic upload (10 items) and it was not successful, then together with Lu it worked out. Continued with testing, and worked out for small upload sizes. 
Since the described upload with 20 items upload not possible anymore. (checked WLAN -> stayed the same, checked collection in qa-gluons -> correctly created, and correctly selected for Upload in Labcam)

reproducable in spot.mpdl.mpg.de/rest

**Comment by tonyqd** [comment]
this happens only on qa-gluons, it works fine on gluons

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg.de
Test date: 28.09.2017
Device: Tablet Nexus 9 Android 5.1.1.

result: ok, not reproducible anymore
