### ISSUE TITLE
Break up Labcam after short press for voice note recording

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#77]
Testserver: qa-gluons
Test date: 22.02.2017
Device: Tablet Nexus 9 
User: standard user

Action: record voice note

-> open voice note window -> short press on microphone icon 

Observation: ->"unfortunately, Labcam has stopped"

Expected result: The correct handling would be "long press", so I would expect an info box with something like "recording wasn't successful" and return to microphone icon

**Comment by tonyqd** [comment]
I have tested it. Now if user shortly press the button, there will be a pop-up showing up to remind user, that he has to long press to record voice note. LabCam will not crash if user only shortly press the button.
