### ISSUE TITLE
Inconsistent upload behaviour of automatic upload

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#78]
Testserver: qa-gluons
Test date: 23.02.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: automatic upload
I repeated this test case 3 times: 
select collection for automatic upload -> "camera" -> take 4 fotos

first result: automatic upload bar in "Local" stopped at 75% -> error message "collection not found" -> but all fotos were uploaded correctly 

second result: automatic upload bar in "Local" stopped at 63% -> but all fotos were uploaded correctly
 
Then I took 13 fotos - result: automatic upload bar in "Local" stopped at 93% -> but all fotos were uploaded correctly

Log out / log in -> with coming back to start page tab "local", the empty grey task bar remained with 0%

third result: automatic upload bar in "Local" stayed at 0% - task in task manager is only startable after log in/log out then correctly uploaded, but name of task changed from "automatic upload" to "4 selected fotos upload to [x]" 

Observations:
Apart from the described cases I repeated automatic upload several times and I found the following patterns which I cannot reproduce on purpouse but come up quite often:

- Taskbar in "Local" stays incompleted, but upload correct
- Taskbar in "local" stays at 0%, task in task manager can be started after log out/log in
- Taskbar in "local" stays at 0%, task in task manager and cannot be started after Log out/log in
- greyed empty taskbar stays after Log out/log in

I always checked if WLAN is active.

**Comment by tonyqd** [comment]
this happens only on qa-gluons, it works fine on gluons

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg.de
Test date: 28.09.2017
Device: Tablet Nexus 9 Android 5.1.1.

result: ok, not reproducible anymore
