### ISSUE TITLE
text note not displayed right after voice note deletion

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#79]
Testserver: qa-gluons
Test date: 23.02.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: delete voice note

select item -> add text note -> add voice note to same item -> delete voice note 

Observation: If voice note is deleted, text note is also not displayed anymore. User has to come back to item so see text note again.

Observation 2:

 -> select item -> open detailed view -> add voice note -> voice note is not displayed immedeately after the creation, only after refreshing the page 
(sometimes it is displayed right after the creation, but cannot reproduce on purpose.)

Expected result: text note stays right away after the deletion of the voice note. and voice note created from detailed view is displayed right away.

**Comment by tonyqd** [comment]
Problem in observation 2 is resolved

**Comment by tonyqd** [comment]
problem solved
