### ISSUE TITLE
Automatic upload breaks up after around 10 fotos 

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#8]
Testcase CAM-13 Upload all taken photos automatically to selected collection (from list)
Testserver: qa-gluons
Test date: 03.08.2016
Device: Tablet Nexus 9Android 5.1.1.

User: user (without imeji admin rights)
Action: take 20 fotos with camera

Observation: after I took the 10th foto (not too fast, took care that camera really "got"the foto), the camera app broke down and I couldn't see any uploaded foto in"local"
after log out /log in,only 4 fotos are displayed in "local")
-> repeating the process, several break up scenarios come up:
1. warning" Unfortunately Labcam has stopped" or
2. display of tab "local", but without fotos (just white) or
3. Labcam closes without warning

Expected result: I can upload 20 fotos.

UPDATE:
Testcase CAM-13 Upload all taken photos automatically to selected collection (from list)
Testserver: qa-gluons
Test date: 04.08.2016

Observation: 
Today I can take 20 fotos, but leaving the camera "Local" is white and the task bar does not show up. -> but fotos are correctly uploaded

**Comment by liyyil** [comment]
can not reproduce with HTC and Samsung
