### ISSUE TITLE
Setting of "other server" not saved

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#81]
Testserver: qa-gluons
Test date: 22.02.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: Log out / Log in to "other server"

log In -> qa-gluons.mpdl.mpg.de/imeji/rest -> log out 

Observation: with coming back, the earlier entered "other server" is not saved and I had to type it in again.

today 23.02., it worked out. (same for spot.mpdl.mpg.de/rest)

update: It came up again: I suppose that the deletion only happens after a certain session time.

Expected result: entry for "Other server" is saved for the next time.

**Comment by tonyqd** [comment]
improved as wished

**Comment by hofmannc** [comment]
Testserver: qa-gluons.mpdl.mpg./rest
Test date: 27.03.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user
Test result: ok
