### ISSUE TITLE
Upload of album not complete

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#83]
Testserver: qa-gluons, spot.mpdl.mpg.de/rest
Test date: 23.02.2017
Device: Tablet Nexus 9 Android 5.1.1.
User: standard user

Action: upload album

select album -> "select all" -> upload -> select collection ->

Observation: 
only one item (out of four) was uploaded to collection

or

upload task wasn't created for the items

**Comment by tonyqd** [comment]
I tried different collections and albums, cannot reproduce the bug.

**Comment by tonyqd** [comment]
this happens only on qa-gluons, it works fine on gluons

**Comment by tonyqd** [comment]
cannot reproduce this on spot.mpdl.mpg.de/rest

**Comment by hofmannc** [comment]
Testserver: qa-imeji.mpdl.mpg.de
Test date: 28.09.2017
Device: Tablet Nexus 9 Android 5.1.1.

result: ok, cannot reproduce on qa-imeji anymore
