### ISSUE TITLE
Upload to "other server" (spot) not working

### ISSUE THREAD

**Issue by hofmannc** [MPDL/LabCam#9]
Testserver: spot.mpdl.mpg.de
Test date: 04.08.2016 
Device: Tablet Nexus 9 Android 5.1.1.
User: hofmann@mpdl.mpg.de

Action: Manual and automatic upload

Observation:
Manual: Taskbar is created, but task is not running (stays at 0%) warning: "failed to create profile"
Automatic: Fotos are taken, but no task bar created 

Expected result: I can upload fotos to spot the same way as to qa-gluons

**Comment by liyyil** [comment]
upload img without metadata to spot(create profile api currently not available on spot)
